# Generated by Django 4.0.5 on 2022-06-06 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wash.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=wash.models.random_id)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('expiration', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=wash.models.random_id)),
                ('name', models.CharField(max_length=100)),
                ('earnings', models.IntegerField()),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('license_plate', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('employee_earnings', models.IntegerField()),
                ('company_earnings', models.IntegerField()),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_type', to='wash.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=wash.models.random_id)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='wash.employee')),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_admin', to=settings.AUTH_USER_MODEL)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_company', to='wash.company')),
                ('id_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_vehicle', to='wash.vehicle')),
                ('typeServices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeservices', to='wash.typeofservices')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
