# Generated by Django 4.0.5 on 2022-06-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='wash.company'),
            preserve_default=False,
        ),
    ]
