# Generated by Django 4.0.5 on 2022-07-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0003_alter_employee_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofservices',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
