# Generated by Django 4.0.5 on 2022-07-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0004_typeofservices_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='typeServices',
        ),
        migrations.AddField(
            model_name='services',
            name='typeServices',
            field=models.ManyToManyField(related_name='typeservices', to='wash.typeofservices'),
        ),
    ]
